language: python
python:
- '2.7'
script:
- make clean
- make release
notifications:
  irc:
    channels:
      - "irc.esper.net#RO"
    skip_join: true
    use_notice: true
    on_success: change
    on_failure: change
    template:
      - "Build #%{build_number} - %{branch} - %{result}"
      - "%{commit_message}"
